apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    env: demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # By default and for convenience, the Kubernetes control plane. will allocate a port from a range (default: 30000-32767)
  selector:
    env: demo